### ISSUE TITLE
Generate app from openapi spec

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/webfakes#31]
Input is the spec, output is the app.

**Comment by gaborcsardi** [comment]
This is a generic tool, written in Java: https://github.com/OpenAPITools/openapi-generator

You can plug in new client or server languages.

**Comment by maelle** [comment]
Does it work with civetweb?

**Comment by gaborcsardi** [comment]
It does not support generating an R server currently, only a client, with R6 and httr it seems.

**Comment by gaborcsardi** [comment]
It seems unlikely now that this would happen, so I am going to close it. It would be still very cool, though.
