### ISSUE TITLE
support recording of responses?

### ISSUE THREAD

**Issue by maelle** [r-lib/webfakes#46]

**Comment by maelle** [comment]
and if not, document a few possible workflows?

**Comment by gaborcsardi** [comment]
I support it would make sense to have a function that creates a test fixture. OTOH, we don't want to reimplement vcr/httptest...

**Comment by maelle** [comment]
Notes from discussion with @gaborcsardi 

Create a vcr app (or vcr middleware?)

First time the app gets a given request
* Create a curl handle, add headers, perform the request
* Use vcr to serialize the interaction to a file.
* Use the response to create `res`

Second time
* For any request, see whether there's a matching one in the files.
* if not use curl.

**Comment by maelle** [comment]
middleware is probably the wrong thing, the thing that'd be added is probably a helper function that you'd call from inside handlers.

**Comment by sckott** [comment]
It would take some work , but I think something like: 

- Export a new vcr function that:
    - takes the request and response from the curl request to make a `VcrResponse` object
    - then serialize to disk
- Export another function to check for matches on disk

**Comment by maelle** [comment]
is "some work" a lot of work?

@gaborcsardi in that case would webfakes take a Suggests dependency on vcr, or should this be an example described somewhere else?

**Comment by gaborcsardi** [comment]
Maybe an example.

**Comment by maelle** [comment]
But not in webfakes, or in webfakes?

**Comment by gaborcsardi** [comment]
Well, if it is in webfakes, then we'd need to suggest it. But it can be an article for a start?

**Comment by gaborcsardi** [comment]
At this point it seems unlikely that this would happen, so I am going to close it. Feel free to reopen it, though!

**Comment by sckott** [comment]
Sounds good
