### ISSUE TITLE
Add links to packages using webfakes?

### ISSUE THREAD

**Issue by maelle** [r-lib/webfakes#66]
Well when there are more.
Even if not naming them, it might be neat for the docs to state at some point that looking at reverse dependencies might be helpful?

**Comment by gaborcsardi** [comment]
That's just the reverse dependencies on CRAN, I suppose. My main issue with lists and links like this is that the list will go out of date, and the links will go stale. In my experience I am not very good at keeping this kind of information current.

**Comment by maelle** [comment]
But what I mean is that you could just have a sentence saying "For examples, look over webfakes' reverse dependencies", because sometimes folks forget you can just do that.
