### ISSUE TITLE
Feature request: expiry/expires_in for OAuth apps

### ISSUE THREAD

**Issue by maelle** [r-lib/webfakes#75]
I am working with an API where in the response returning a token, the field with the expiration time is called "expires_in", not "expiry". Would it make sense or be too cumbersome to add flexibility in this regard? I can probably just make my own code more flexible though.

**Comment by gaborcsardi** [comment]
I am going to close this now, you probably solved this already a different way. But if you still need it, feel free to reopen and/or to submit a PR. I looked at it quickly, but it is not obvious which field in which response I need to update, and I also cannot test, so I didn't make an attempt at it.
