### ISSUE TITLE
fails when (encoded) spaces are in URL

### ISSUE THREAD

**Issue by mkoohafkan** [r-lib/webfakes#95]
It appears that `webfakes` does not support urls with encoded (.e.g, `%20`) spaces:

```r
app = webfakes::new_app()
app$get("/testnospace", function(req, res) {
  res$send("url with no space!")
})
app$get("/test%20space", function(req, res) {
  res$send("url with a space!")
})

web <- webfakes::local_app_process(app)

httr::GET(web$url("/testnospace"))$status
#> 200
httr::GET(web$url("/test%20space"))$status
#> 404
```

Is there a way around this, or am I misunderstanding something?

**Comment by gaborcsardi** [comment]
```r
app$get("/test space", function(req, res) {
  res$send("url with a space!")
})
web <- webfakes::local_app_process(app)
httr::GET(web$url("/test%20space"))$status
# [1] 200
```

**Comment by mkoohafkan** [comment]
Thanks @gaborcsardi. In my case the I am mocking an API call that returns a URL, and the returned URL is already encoded. If I understand you correctly, the way to mock the returned URL is to specify the unencoded URL instead.

**Comment by gaborcsardi** [comment]
I don't understand this, sorry. Are you saying that you want to return an encoded URL? You can do that:
```r
app <- webfakes::new_app()
app$get("/test", function(req, res) {
  res$send(utils::URLencode("https://url with a space!"))
})
web <- webfakes::local_app_process(app)
httr::content(httr::GET(web$url("/test")))
```

**Comment by mkoohafkan** [comment]
No worries, it is just a small detail with how to define the mock queries but your example explains the issue. I am mocking an API where one call returns a URL to a file (which is constructed on the fly and is encoded), and also mocking the call to download said file. My original approach was

```r
app = webfakes::new_app()
app$get("/getbinary/tm/8", function(req, res) {
  res$
    set_status(200L)$
    send(paste0(gsub(req$path, "", req$url),
        "mock/a%20file%20with%20spaces.dat"))
})
app$get("/data-catalog/binData/a%20file%20with%20spaces.dat", function(req, res) {
  res$
    set_status(200L)$
    send_file("mock/a file with spaces.dat")
})
```
But the second mock didn't work. I instead needed to do
```r
app$get("/data-catalog/binData/a file with spaces.dat", function(req, res) {
  res$
    set_status(200L)$
    send_file("mock/a file with spaces.dat")
})
```

In other words, my mistake was defining the mocked URL with spaces already encoded.
